server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: container-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_logging_antystics_app']
        regex: "true"
        action: keep
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(?P<name>[^/]+)'
        target_label: container
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_label_logging_antystics_service']
        target_label: service
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
        replacement: '${1}'
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: '["@l"]'
            message: '["@m"]'
            eventType: EventType
            correlationId: CorrelationId
            exception: '["@x"]'
          on_error: keep
      - labels:
          level:
          eventType:
          correlationId:

