server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: container-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Set job label (this should be automatic, but being explicit)
      - target_label: job
        replacement: container-logs
      # Set container label - use simplest possible approach
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '(.*)'
        replacement: '${1}'
      # Remove leading slash from container name
      - source_labels: ['container']
        target_label: container  
        regex: '/(.+)'
        replacement: '${1}'
      # TEMPORARILY REMOVE FILTER - scrape ALL containers to test
      # - source_labels: ['__meta_docker_container_label_logging_antystics_app']
      #   regex: "true"
      #   action: keep
    pipeline_stages:
      - docker: {}
      - output:
          source: message
