apiVersion: 1

contactPoints:
  - name: default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: tmierzejowski@gmail.com

notificationPolicies:
  - receiver: default-email
    group_by:
      - alertname
    matchers: []
    continue: false

